CREATE LOGIN [MapaInversiones]
    WITH PASSWORD = N'7jyaptdqisi***REMOVED***~zfMdp|axyhnmsFT7_&#$!~<***REMOVED***opkdoxojpnc', SID = 0x213B728A7D70DA4EAE3EC50E6DA5ABB4, DEFAULT_LANGUAGE = [Español], CHECK_POLICY = OFF;

